baseURL = ""

title = "Joseph L. Sanders"

languageCode = "en-us"
defaultcontentlanguage = "en"

theme = "hugo-coder"
pygmentsstyle = "friendly"

[params]
    author = "Joseph L. Sanders"
    info = "Errata Ad Nauseam"
    avatarurl = "/jls_profile.png"

    colorscheme = "light"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 4

[[params.social]]
    url = "mailto:contact@sandco.io"
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1

[[params.social]]
    url = "https://github.com/jls83/"
    name = "GitHub"
    icon = "fab fa-github fa-2x"
    weight = 2

[[params.social]]
    url = "https://www.linkedin.com/in/josephlsanders/"
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3

[[params.social]]
    url = "https://stackoverflow.com/users/5209981/jls83"
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 4
